### ISSUE TITLE
Error when running "make release-static-win64"

### ISSUE THREAD

**Issue by divesummit** [oxen-io/oxen-core#1358]
Followed all the steps when on Windows as described on [https://github.com/loki-project/loki-core](url)

When I run  "make release-static-win64" in the ~/loki directory it results

"mkdir -p build/"MINGW64_NT-10.0-18363/_HEAD_detached_at_v8.1.4_"/release
cd build/"MINGW64_NT-10.0-18363/_HEAD_detached_at_v8.1.4_"/release && cmake -G "MSYS Makefiles" -D STATIC=ON -D ARCH="x86-64" -D BUILD_64=ON -D CMAKE_BUILD_TYPE=Release -D BUILD_TAG="win-x64" -D CMAKE_TOOLCHAIN_FILE=../../../../cmake/64-bit-toolchain.cmake -D MSYS2_FOLDER=C:/msys64/ ../../../.. && make
-- CMake version 3.18.4
-- The CXX compiler identification is unknown
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:53 (project):
  The CMAKE_CXX_COMPILER:

    x86_64-w64-mingw32-g++-posix

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:53 (project):
  The CMAKE_C_COMPILER:

    x86_64-w64-mingw32-gcc-posix

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "C:/msys64/home/Admn/loki/build/MINGW64_NT-10.0-18363/_HEAD_detached_at_v8.1.4_/release/CMakeFiles/CMakeOutput.log".
See also "C:/msys64/home/Admn/loki/build/MINGW64_NT-10.0-18363/_HEAD_detached_at_v8.1.4_/release/CMakeFiles/CMakeError.log".
make: *** [Makefile:163: release-static-win64] Error 1"

**Am I doing something wrong? Everything seemed to go fine up to this point.  

Please someone advise.

Thanks**

**Comment by jagerman** [comment]
I haven't built for Windows actually *on* Windows in a long time because it's generally a lot easier to build for Windows on Linux (perversely).

How in this case I don't think you want to use that Makefile target at all (it's really designed for building for windows on a linux system), but instead want to do something like:
```
mkdir build
cd build
cmake ..
make -j4
```
but there are likely to be a bunch of library and compilers packages that you need along the way to make it actually build.

**Comment by coreagex** [comment]
> I haven't built for Windows actually _on_ Windows in a long time because it's generally a lot easier to build for Windows on Linux (perversely).
> 
> How in this case I don't think you want to use that Makefile target at all (it's really designed for building for windows on a linux system), but instead want to do something like:
> 
> ```
> mkdir build
> cd build
> cmake ..
> make -j4
> ```
> 
> but there are likely to be a bunch of library and compilers packages that you need along the way to make it actually build.

Not correct, its misleading

**Comment by coreagex** [comment]
> Followed all the steps when on Windows as described on [https://github.com/loki-project/loki-core](url)
> 
> When I run "make release-static-win64" in the ~/loki directory it results
> 
> "mkdir -p build/"MINGW64_NT-10.0-18363/_HEAD_detached_at_v8.1.4_"/release
> cd build/"MINGW64_NT-10.0-18363/_HEAD_detached_at_v8.1.4_"/release && cmake -G "MSYS Makefiles" -D STATIC=ON -D ARCH="x86-64" -D BUILD_64=ON -D CMAKE_BUILD_TYPE=Release -D BUILD_TAG="win-x64" -D CMAKE_TOOLCHAIN_FILE=../../../../cmake/64-bit-toolchain.cmake -D MSYS2_FOLDER=C:/msys64/ ../../../.. && make
> -- CMake version 3.18.4
> -- The CXX compiler identification is unknown
> -- The C compiler identification is unknown
> CMake Error at CMakeLists.txt:53 (project):
> The CMAKE_CXX_COMPILER:
> 
> ```
> x86_64-w64-mingw32-g++-posix
> ```
> 
> is not a full path and was not found in the PATH.
> 
> Tell CMake where to find the compiler by setting either the environment
> variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
> to the compiler, or to the compiler name if it is in the PATH.
> 
> CMake Error at CMakeLists.txt:53 (project):
> The CMAKE_C_COMPILER:
> 
> ```
> x86_64-w64-mingw32-gcc-posix
> ```
> 
> is not a full path and was not found in the PATH.
> 
> Tell CMake where to find the compiler by setting either the environment
> variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
> the compiler, or to the compiler name if it is in the PATH.
> 
> -- Configuring incomplete, errors occurred!
> See also "C:/msys64/home/Admn/loki/build/MINGW64_NT-10.0-18363/_HEAD_detached_at_v8.1.4_/release/CMakeFiles/CMakeOutput.log".
> See also "C:/msys64/home/Admn/loki/build/MINGW64_NT-10.0-18363/_HEAD_detached_at_v8.1.4_/release/CMakeFiles/CMakeError.log".
> make: *** [Makefile:163: release-static-win64] Error 1"
> 
> **Am I doing something wrong? Everything seemed to go fine up to this point.
> 
> Please someone advise.
> 
> Thanks**

Just doing 
```shell 
mkdir build and cd build and cmake ...
```
will prompt you to Building for: Visual Studio  and not msys. So you have to do alot to make it work with msys. It was deliberately removed still dont know why.
