### ISSUE TITLE
Daemon has not been started in service node mode, please relaunch with --service-node flag.

### ISSUE THREAD

**Issue by fiorthnir** [oxen-io/oxen-core#1404]
Hello, 
Yesterday I have install oxen on my OVH vps machine and today I try to setup my new oxen service node by following the documentation (https://docs.oxen.io/using-the-oxen-blockchain/oxen-service-node-guides/full-service-node-setup-guide).
The server is fully syncronized, I check that on the logs, and all the services are running. 
The problem is that when I launch the following command:

> oxend prepare_registration

At the final step (the one to validate all the informations) I got the following error: 

> Error: Failed to validate registration arguments; check the addresses and registration parameters and that the Daemon is running with the '--service-node' flag: JSON RPC returned an error response: Daemon has not been started in service node mode, please relaunch with --service-node flag.

I'm not sure about what to do now. 
Should I edit one of the oxen-node.service files to add that flag? 

- /var/lib/systemd/deb-systemd-helper-enabled/multi-user.target.wants/oxen-node.service
- /usr/lib/systemd/system/oxen-node.service
- /etc/systemd/system/multi-user.target.wants/oxen-node.service
- /sys/fs/cgroup/pids/system.slice/oxen-node.service
- /sys/fs/cgroup/memory/system.slice/oxen-node.service
- /sys/fs/cgroup/devices/system.slice/oxen-node.service
- /sys/fs/cgroup/systemd/system.slice/oxen-node.service
- /sys/fs/cgroup/unified/system.slice/oxen-node.service

Or maybe there is a command line? 

If you need more information I'll stay fully available today. 
Thank you for the help.

**Comment by fiorthnir** [comment]
The command `systemctl cat oxen-node` show me the service configuration located here `/lib/systemd/system/oxen-node.service`. 
Should I add the flag --service-node at the line :

> ExecStart=/usr/bin/oxend --non-interactive --config-file /etc/oxen/oxen.conf

So it would be:

> ExecStart=/usr/bin/oxend --service-node --non-interactive --config-file /etc/oxen/oxen.conf

?

**Comment by fiorthnir** [comment]
Ok... really easy. Just a restart of the oxen-node service resolve my issue.

**Comment by jagerman** [comment]
For future reference of people who might stumble across this:

You should never need to change the service files; any command line options can be added to the /etc/oxen/oxen.conf file; in this case with a line `service-node=1` is equivalent to starting it with `--service-node` when the service restarts.
