### ISSUE TITLE
Is it possible to unstake from a node? 

### ISSUE THREAD

**Issue by EvanTedesco** [oxen-io/oxen-core#1429]
Hello,  

I registered a node with 2 wallet addresses specified, but one  of the participants never committed his stake.  Is there some way that I can get my stake back or deregister the node so that I can stake in another pool?

**Comment by jagerman** [comment]
I assume you mean a reserved contribution spot?

You can submit a stake unlock request for a partially staked node to initiate the 15-day unlock timer, but unfortunately you'll still have to wait for the unlock period if the participant doesn't commit his stake.

**Comment by EvanTedesco** [comment]
Thanks for the timely answer.  I wish it were different haha.
