### ISSUE TITLE
Unable to connect hardware wallet to cli

### ISSUE THREAD

**Issue by nicprov** [oxen-io/oxen-core#1510]
**Describe the bug**
I am trying to connect my Ledger Nano S to my local Oxen wallet using the CLI. I get the following error message: Error: failed to generate new wallet: No device found. (Is the device running with the wallet app opened?)

**To Reproduce**
1. Open wallet cli: ./oxen-wallet-cli --generate-from-device ledger
2. Enter an arbitrary password

I tried running the steps above both with the Ledger Live bridge open and closed (as this is usually required for other wallets). If I try to open the ledger live in bridge mode, I run the following command:  sudo ./ledger-live-desktop-2.36.3-linux-x86_64.AppImage ledgerlive://bridge?appName=Oxen --no-sandbox

**Expected behaviour**
What is the expected behaviour if the steps above are followed:

As mentioned in [this guide](https://docs.oxen.io/using-the-oxen-blockchain/oxen-wallet-guides/oxen-ledger-wallet-usage-cli-wallet#steps-to-generate-a-wallet-using-the-ledger), it should prompt my ledger for permission and then create the wallet which is does not do.

**Current Behaviour**
What is the current behaviour if the steps to reproduce are followed:

Right now, as soon as I run the command mentioned above to generate the wallet from the device, I get the following error: No device found. (Is the device running with the wallet app opened?).

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional Information (please complete the following information):**
 - Operating System: Debian 11
-  Local or Remote node: Local node
 - Version of Loki daemon, or most recent commit hash: Latest (0.9.2)

**Comment by darcys22** [comment]
Hi Nicholas,

Yeah there were some updates that have been included in #1467 so you will need to be running the latest dev branch compiled with libhidapi to connect to the ledger. 

My understanding of the bridge is to give a sandboxed app in a web browser access to USB. We haven't needed it as our wallet is a native app and already has access to the hardware.

However the ledger functionality is in early stages and we are still working with ledger to get the app onto ledger live. So you also have to compile the oxen ledger app yourself and unsure if you have managed this yet? 

Cheers
Sean

**Comment by nicprov** [comment]
@darcys22 Thanks a lot for your help! Compiled the dev branch with libhidapi-dev installed and it works fine now!
