### ISSUE TITLE
print_locked_stakes in the CLI wallet produces a lot of superfluous whitespace.

### ISSUE THREAD

**Issue by ianmacd** [oxen-io/oxen-core#1575]
**Describe the bug**

`print_locked_stakes` produces a lot of unnecessary whitespace.

At first, I thought it wasn't printing any data at all, but when I scrolled back far enough in my buffer, I saw that it was.

**To Reproduce**

* Run the command line wallet.
* Run the `print_locked_stakes` command.

**Expected behaviour**

Data about the wallet's locked stakes should be nicely printed.

**Current Behaviour**

Data about the wallet's locked stakes is printed, but interspersed with huge amounts of whitespace.

**Additional Information (please complete the following information):**

OS: Linux (Fedora 36)
Version: Oxen 'Wistful Wagyu' (v10.1.2-d826fbee0-dev) (compiled by me)

**Comment by jagerman** [comment]
That must be a fairly recent breakage; that wasn't doing that a couple months ago.

**Comment by ianmacd** [comment]
> That must be a fairly recent breakage; that wasn't doing that a couple months ago.

I couldn't remember it either, but didn't want to claim something I couldn't be sure of.

**Comment by jagerman** [comment]
This display code... has some other bugs too.
