### ISSUE TITLE
Wallets with less than 25% stake are able to unlock prior to 30 days.

### ISSUE THREAD

**Issue by fortycentface** [oxen-io/oxen-core#1582]
Node unlock was requested less than an hour after full stake. None of the contributing wallets have over 25% stake. The operator did not initiate the unlock.

**Comment by ianmacd** [comment]
What's the pubkey of the node?

**Comment by fortycentface** [comment]
c5b2990af0d4abe830b597da31ae077ac60397657eefefa6330b0bbbe4790ebc

**Comment by darcys22** [comment]
Link on oxen observer:
https://oxen.observer/sn/c5b2990af0d4abe830b597da31ae077ac60397657eefefa6330b0bbbe4790ebc/1#more_details

Here is the unlokck transaction:
https://oxen.observer/tx/950e3a078d6849586f24c406c62eadd908b743b29474f30e14050314cf751bbd/1#more_details

Was the contributor of 231 oxen. Service node became active on block 1107132 and the requested unlock occurred on block 1107152

At first glance it appears this shouldnt have happened.

**Comment by ianmacd** [comment]
> Link on oxen observer: https://oxen.observer/sn/c5b2990af0d4abe830b597da31ae077ac60397657eefefa6330b0bbbe4790ebc/1#more_details
> 
> Here is the unlokck transaction: https://oxen.observer/tx/950e3a078d6849586f24c406c62eadd908b743b29474f30e14050314cf751bbd/1#more_details
> 
> Was the contributor of 231 oxen. Service node became active on block 1107132 and the requested unlock occurred on block 1107152

I've learnt something today: I didn't realise you could see from the key image who the initiator of an unlock is. That's handy.

> At first glance it appears this shouldnt have happened.

Indeed. That node has been running only a few days.

**Comment by darcys22** [comment]
addressed in #1583
