### ISSUE TITLE
Over-staking possible when competing stakes are submitted

### ISSUE THREAD

**Issue by jagerman** [oxen-io/oxen-core#747]
Reported on Telegram today:

> I got 8200 loki staked in a service node but it locked my 9700 as that is the amount I tried to stake at the time. In between staking and getting confirmed someone else also staked so there was only space on service node for 8200 loki. Is there a way to release the locked 1500 loki without destaking the entire 9700? The 1500 has not contributed to the service node and I am not being rewarded for so I'd like to  stake it in another service node.

I haven't verified this, but based on the above it seems we don't enforce a maximum on the staked amount.  So if you find a SN with X available, and you stake Y, but meanwhile someone else has staked Z and Y+Z > X then your stake of Y still goes through, but it counts as completing the stake for whatever is left (X-Z), which can be (much) less than Y.

As a result, you end up with Y locked, but only X-Z staked.

A proposed solution here: don't accept stakes as valid if the available contribution room is less than 99% of the stake amount.  (The buffer is so that if people slightly overstake by rounding up to the nearest LOKI it will still be okay--it could probably be higher than 99%, but an extra 1% staked is probably not a big deal).

**Comment by CryptoFirefly** [comment]
Additional Enhancement on Viewing Pending Stake Txn on Loki Blocks for the Node: 
I see on Loki-blocks it is possible to view pending Staking transactions within the table that displays the pending transactions. 

It would be a great enhancement if the pending transaction for the relevant node is displayed on the Service Node page while it is waiting to be mined. As at times these transactions take 5-10 mins to be mined. 

e.g. If the Total stake is 20,000 Loki. And the Op put in 5000 Loki.
Now with 15k left, if i see someone has a pending txn for 5k Loki stake, i can take a calculated call to stake remaining 10k. Yes, if i stake 15k with the above enhancement it wont go through. But i may have to wait 10 blocks to retry, if the txn failed. And i may lose the spot and to a new staker this may be a not so good experience. 

This info is already possible to be view, only putting it on the SN's page makes it easier to spot, which would be a good user friendly enhancement.
